version: "3.0"

services:
    selenium:
        image: selenium/standalone-firefox
        networks: 
            - net
        ports:
            - "4444:4444"
        shm_size: "2g"
   
    gisaid_scrapper:
        image: pawelkulig/gisaid_scrapper:1.0
        depends_on: 
            - selenium
        build: .
        networks: 
            - net
        volumes: 
            - .:/home

networks:
    net:

